In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import simdkalman
from tqdm.notebook import tqdm

In [2]:
T = 1.0
# 下の行列どこから出てきた？ -> パラメータチューニングから
# 状態遷移マトリックス
state_transition = np.array([[1, 0, T, 0, 0.5 * T ** 2, 0], [0, 1, 0, T, 0, 0.5 * T ** 2], [0, 0, 1, 0, T, 0],
                             [0, 0, 0, 1, 0, T], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1]])
# 対角行列
process_noise = np.diag([1e-5, 1e-5, 5e-6, 5e-6, 1e-6, 1e-6]) + np.ones((6, 6)) * 1e-9
observation_model = np.array([[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0]])
observation_noise = np.diag([5e-5, 5e-5]) + np.ones((2, 2)) * 1e-9

kf = simdkalman.KalmanFilter(
        state_transition = state_transition,
        process_noise = process_noise,
        observation_model = observation_model,
        observation_noise = observation_noise)

In [16]:
def apply_kf_smoothing(df, kf_=kf):
    unique_paths = df[['collectionName', 'phoneName']].drop_duplicates().to_numpy()
#     print(unique_paths)
    for collection, phone in tqdm(unique_paths):
        cond = np.logical_and(df['collectionName'] == collection, df['phoneName'] == phone)
        data = df[cond][['latDeg', 'lngDeg']].to_numpy()
        print(len(data))
        data = data.reshape(1, len(data), 2) # 1, 縦=len(data), 横=2(lat,lng)
        '''
        1740
        [[[  37.4235753 -122.0940914]
          [  37.4235777 -122.094101 ]
          [  37.4235733 -122.0941109]
          ...
          [  37.6458135 -122.4055989]
          [  37.6458118 -122.4056082]
          [  37.6458101 -122.4056112]]]
        1746
        [[[  37.4235738 -122.0941372]
          [  37.4235734 -122.094153 ]
          [  37.4235781 -122.0941481]
          ...
          [  37.6457707 -122.4055646]
          [  37.6457367 -122.4053947]
          [  37.6458503 -122.4055982]]]
          .
          .
          .

        '''
#         print(data)
        smoothed = kf_.smooth(data)
        df.loc[cond, 'latDeg'] = smoothed.states.mean[0, :, 0]
        df.loc[cond, 'lngDeg'] = smoothed.states.mean[0, :, 1]
    return df

In [17]:
data_path = Path("../input/google-smartphone-decimeter-challenge")

# ファイルを順に開いていく
truths = (data_path / 'train').rglob('ground_truth.csv')
    # returns a generator

df_list = []
cols = ['collectionName', 'phoneName', 'millisSinceGpsEpoch', 'latDeg', 'lngDeg']

for t in tqdm(truths, total=73):
    df_phone = pd.read_csv(t, usecols=cols)  
    df_list.append(df_phone)
df_truth = pd.concat(df_list, ignore_index=True)

df_basepreds_kf = apply_kf_smoothing(pd.read_csv('../input/google-smartphone-decimeter-challenge/baseline_locations_train.csv', usecols=cols))
df_all = df_truth.merge(df_basepreds_kf, how='inner', on=cols[:3], suffixes=('_truth', '_basepred'))

  0%|          | 0/73 [00:00<?, ?it/s]

  0%|          | 0/73 [00:00<?, ?it/s]

1740
[[[  37.4235753 -122.0940914]
  [  37.4235777 -122.094101 ]
  [  37.4235733 -122.0941109]
  ...
  [  37.6458135 -122.4055989]
  [  37.6458118 -122.4056082]
  [  37.6458101 -122.4056112]]]
1746
[[[  37.4235738 -122.0941372]
  [  37.4235734 -122.094153 ]
  [  37.4235781 -122.0941481]
  ...
  [  37.6457707 -122.4055646]
  [  37.6457367 -122.4053947]
  [  37.6458503 -122.4055982]]]
1770
[[[  37.690209  -122.3923213]
  [  37.6901875 -122.3923194]
  [  37.6901978 -122.3923276]
  ...
  [  37.4232315 -122.0902211]
  [  37.4232301 -122.0902397]
  [  37.4232358 -122.0902183]]]
577
[[[  37.6905551 -122.3929467]
  [  37.69068   -122.3933336]
  [  37.690262  -122.3921765]
  ...
  [  37.5869385 -122.3460696]
  [  37.5869285 -122.3456506]
  [  37.5869075 -122.3452327]]]


KeyboardInterrupt: 

In [17]:
# simplified haversine distance
def calc_haversine(lat1, lon1, lat2, lon2):
    """Calculates the great circle distance between two points
    on the earth. Inputs are array-like and specified in decimal degrees.
    """
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2

    c = 2 * np.arcsin(a**0.5)
    dist = 6_367_000 * c
    return dist

In [18]:
df_all['dist'] = calc_haversine(df_all.latDeg_truth, df_all.lngDeg_truth, 
    df_all.latDeg_basepred, df_all.lngDeg_basepred)

print(f'mean error on train dataset: {df_all.dist.mean():.3f}m - slightly better than the baseline, but still a lot of improvements are needed')

mean error on train dataset: 3.725m - slightly better than the baseline, but still a lot of improvements are needed


In [9]:
test_base = pd.read_csv(
    '../input/google-smartphone-decimeter-challenge/baseline_locations_test.csv')

sub = pd.read_csv('../input/google-smartphone-decimeter-challenge/sample_submission.csv')

kf_smoothed_baseline = apply_kf_smoothing(test_base)
sub = sub.assign(
    latDeg = kf_smoothed_baseline.latDeg,
    lngDeg = kf_smoothed_baseline.lngDeg
)
sub.to_csv('../output/submission01.csv', index=False)

  0%|          | 0/48 [00:00<?, ?it/s]